#!/bin/sh
#
pkg=lme4.0
npkg=lme4
#
GREP=/bin/grep
#
cd `dirname $0`/..
if [ ! -d $pkg ]
then
    echo "'$pkg' is not a subdirectory of `pwd` --- exiting"
    exit 1
fi
# EXCL='--exclude=.svn --exclude=CVS --exclude=auto --exclude=*.txt --exclude=*32'
# tar cfh - $EXCL --exclude='*~' --exclude='00*' $pkg \
#  | (cd /tmp ; rm -rf T$pkg; mkdir T$pkg; cd T$pkg; tar xf - )
cd /tmp ; rm -rf T$pkg; mkdir T$pkg
DD=/tmp/T$pkg; test -d $DD || (echo '** '"$DD"' is not a valid directory'; exit 2)
cd $DD
svn export --quiet svn://svn.r-forge.r-project.org/svnroot/lme4/pkg/${pkg} $pkg
test -d $pkg || (echo '** '"$pkg"' is not a valid directory'; exit 2)
ls -l $pkg
cd $pkg
## Remove the  "lme4 -> lme4.0" function:
rm -f R/oldconv.R man/convert_old_lme4.Rd
sed -i.bak -e '/convert_old_lme4/d' NAMESPACE
sed -i.bak -e '/^Date:/s/:.*/: '`date --iso`'/; /to lme4.0/,/lme4.0 until/d' DESCRIPTION
# List of files that need to be "patched":
flist=`$GREP -r --no-messages -l "$pkg" . | $GREP -Fvw .svn | $GREP -vE '[-+#~0-9]$'`
perl -pi.bak -e "s/$pkg/$npkg/g" $flist
cd ..
## now in /tmp :
mv $pkg $npkg
R CMD build $npkg
ls -ld `pwd`/${npkg}*
